### ISSUE TITLE
model.fit raises an error

### ISSUE THREAD

**Issue by luciforthefriends** [ravasconcelos/spoken-digits-recognition#1]
Hi, I am Lucas.

First of all, I want to thank you for sharing this work.
I am testing your scripts and I am getting an error at the model.fit part (section 2 - speaker-recognition script).

I will leave the error here (***)
Any clues about what might be the problem?

Thx and happy codding!

(***)
Epoch 1/50
2021-11-29 17:56:33.635015: W tensorflow/core/framework/op_kernel.cc:1722] OP_REQUIRES failed at cast_op.cc:121 : UNIMPLEMENTED: Cast string to float is not supported
Traceback (most recent call last):
  File "c:/Users/Luci/Desktop/spoken-digits-recognition-master/src/mySpeakerRecognition.py", line 172, in <module>
    history = model.fit(X_train,
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Luci\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError:  Cast string to float is not supported
         [[node Cast_1
 (defined at C:\ProgramData\Anaconda3\lib\site-packages\keras\metrics.py:716)
]] [Op:__inference_train_function_851]

Errors may have originated from an input operation.
Input Source operations connected to node Cast_1:
In[0] IteratorGetNext (defined at C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py:866)

Operation defined at: (most recent call last)
>>>   File "c:/Users/Luci/Desktop/spoken-digits-recognition-master/src/mySpeakerRecognition.py", line 172, in <module>
>>>     history = model.fit(X_train,
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1216, in fit
>>>     tmp_logs = self.train_function(iterator)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 878, in train_function
>>>     return step_function(self, iterator)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 867, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 817, in train_step
>>>     self.compiled_metrics.update_state(y, y_pred, sample_weight)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 460, in update_state
>>>     metric_obj.update_state(y_t, y_p, sample_weight=mask)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\metrics_utils.py", line 73, in decorated
>>>     update_op = update_state_fn(*args, **kwargs)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\metrics.py", line 177, in update_state_fn
>>>     return ag_update_state(*args, **kwargs)
>>>
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\metrics.py", line 716, in update_state
>>>     y_true = tf.cast(y_true, self._dtype)
>>>
PS C:\Users\Luci\Desktop\spoken-digits-recognition-master\src>

**Comment by ahmedai91** [comment]
@luciforthefriends  did you solve this issue?

**Comment by GricksNT** [comment]
![image](https://user-images.githubusercontent.com/58885592/144754790-5d48690b-c0bc-4ce6-9d31-a4afb23e6e8f.png)
Solved: in the preProcessData fonction , speaker should equal 0 not "0" ! should be numerical not string

**Comment by luciforthefriends** [comment]
> ![image](https://user-images.githubusercontent.com/58885592/144754790-5d48690b-c0bc-4ce6-9d31-a4afb23e6e8f.png) Solved: in the preProcessData fonction , speaker should equal 0 not "0" ! should be numerical not string

Thank you!

**Comment by andresbenintende** [comment]
Hello everyone!
I had a similar problem with the otherfile ([spoken-digits-recognition.ipynb](https://github.com/ravasconcelos/spoken-digits-recognition/blob/master/src/spoken-digits-recognition.ipynb)) and the solution I found was the following:

![image](https://user-images.githubusercontent.com/57186267/193433050-13e46f13-3c98-4f53-b7e1-089ac2dc1597.png)


I hope this helps in case someone else has this problem.
